### ISSUE TITLE
../drivers/input/touchscreen/stm/ftm4_ts.c:2531:1: error: unused label 'exit' [-Werror,-Wunused-label]

### ISSUE THREAD

**Issue by kkuehl** [nathanchance/wahoo#4]
git diff
diff --git a/drivers/input/touchscreen/stm/ftm4_ts.c b/drivers/input/touchscreen/stm/ftm4_ts.c
index 0a03c193c862..b626ed199244 100644
--- a/drivers/input/touchscreen/stm/ftm4_ts.c
+++ b/drivers/input/touchscreen/stm/ftm4_ts.c
@@ -2528,7 +2528,6 @@ static int fts_resume(struct i2c_client *client)
 
        fts_start_device(info);
 
-exit:
 #ifdef CONFIG_WAKE_GESTURES
        if (wg_changed) {
                wg_switch = wg_switch_temp;

**Comment by nathanchance** [comment]
How are you getting this warning? I'm building with GCC 4.9.4, GCC 7.3.0, Clang 5.0, Clang 6.0, and Clang 7.0 all with `-Werror` and have no issues.

**Comment by nathanchance** [comment]
Oh, my guess is you are not using my defconfig (flash-taimen_defconfig or flash-walleye_defconfig). However, this is a legitimate issue.

**Comment by kkuehl** [comment]
I wasn't using your defconfig, trying that now. Thanks!

**Comment by kkuehl** [comment]
-Wunused-label is what exposed this, thanks for the quick patch.
