### ISSUE TITLE
maple scheduler seems broken

### ISSUE THREAD

**Issue by kkuehl** [nathanchance/wahoo#5]
I am checking out this version of your kernel:
git log | head
commit 05af6729478a167c82275160eeb7b330e125f2c2
Merge: 29a428f349a7 5dcbc71849b8
Author: Nathan Chancellor <natechancellor@gmail.com>
Date:   Tue Apr 24 00:56:10 2018 -0700

Here is the error, but I don't know where you have merged your maple scheduler from.

../block/maple-iosched.c:89:6: error: use of undeclared identifier 'state_lcd_is_on'
        if (state_lcd_is_on && mdata->fifo_expire[sync][dir]) {
            ^
../block/maple-iosched.c:217:7: error: use of undeclared identifier 'state_lcd_is_on'
                if (state_lcd_is_on && mdata->starved >= mdata->writes_starved)
                    ^
../block/maple-iosched.c:219:13: error: use of undeclared identifier 'state_lcd_is_on'
                else if (!state_lcd_is_on && mdata->starved >= 1)
                          ^
3 errors generated.

**Comment by nathanchance** [comment]
```bash
nathan@flashbox ~/kernels/flash/wahoo (staging) $ ag state_lcd_is_on block/maple-iosched.c
```

That doesn't look like my kernel.

**Comment by kkuehl** [comment]
$ git clone https://github.com/nathanchance/wahoo.git
Cloning into 'wahoo'...
remote: Counting objects: 4790201, done.
remote: Compressing objects: 100% (886/886), done.
remote: Total 4790201 (delta 962), reused 992 (delta 719), pack-reused 4788595
Receiving objects: 100% (4790201/4790201), 864.55 MiB | 20.00 MiB/s, done.
Resolving deltas: 100% (4036912/4036912), done.
Checking out files: 100% (56463/56463), done.
$ cd wahoo/
$ git log | head
commit 05af6729478a167c82275160eeb7b330e125f2c2
Merge: 29a428f349a7 5dcbc71849b8
Author: Nathan Chancellor <natechancellor@gmail.com>
Date:   Tue Apr 24 00:56:10 2018 -0700

    Merge remote-tracking branch 'als/android-msm-wahoo-4.4-oreo-m2' into oreo-m2
    
    Signed-off-by: Nathan Chancellor <natechancellor@gmail.com>

commit 5dcbc71849b813aa78eb987753db9aabeb3f2d92

$ git status
On branch oreo-m2
Your branch is up-to-date with 'origin/oreo-m2'.

nothing to commit, working tree clean

Let me double check

**Comment by kkuehl** [comment]
using your default config and everything built fine.
