### ISSUE TITLE
One error while making the project

### ISSUE THREAD

**Issue by spaul13** [nathanchance/wahoo#6]
While making this project using "make -j4", right now I am getting this one error

_**lib/dynamic_debug.c: In function 'trim_prefix':
lib/dynamic_debug.c:71:13: error: overflow in implicit constant conversion [-Werror=overflow]
  int skip = strlen(__FILE__) - DSTRLEN("lib/dynamic_debug.c");
             ^
  CC      net/ipv4/ip_sockglue.o
  CC      lib/checksum.o
cc1: all warnings being treated as errors
scripts/Makefile.build:299: recipe for target 'lib/dynamic_debug.o' failed
make[1]: *** [lib/dynamic_debug.o] Error 1
make[1]: *** Waiting for unfinished jobs....
  CC      net/ipv6/af_inet6.o
Makefile:1046: recipe for target 'lib' failed
make: *** [lib] Error 2
make: *** Waiting for unfinished jobs....**_

Everything else compiled fine. Can u plz tell me why I am getting this error and how to resolve this one?

**Comment by nathanchance** [comment]
It looks like you aren't using my defconfig, you need to use `flash_defconfig`.

**Comment by spaul13** [comment]
Thanks for the quick reply. Now, I tried the flash_defconfig one. But still a small error is there

  **_DTBOIMG arch/arm64/boot/dtbo.img
/bin/sh: 1: mkdtimg: not found
arch/arm64/boot/Makefile:56: recipe for target 'arch/arm64/boot/dtbo.img' failed
make[1]: *** [arch/arm64/boot/dtbo.img] Error 127
arch/arm64/Makefile:200: recipe for target 'dtbo.img' failed
make: *** [dtbo.img] Error 2
make: *** Waiting for unfinished jobs...._**

can u please tell me how to resolve this error?

**Comment by nathanchance** [comment]
Download https://github.com/nathanchance/scripts/blob/master/bin/mkdtimg and add it to your path.

**Comment by spaul13** [comment]
**_/bin/sh: 1: lz4c: not found
make[1]: *** [arch/arm64/boot/Image.lz4] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [Image.lz4-dtb] Error 2_**

can u please give me the relevant package for this? Thanks for the earlier one its got solved.

**Comment by msfjarvis** [comment]
Install lzop and start using Google to find things rather than spam maintainers

**Comment by nathanchance** [comment]
It's `lz4` on Arch Linux, it'll probably be similar for other distros. Any time you get a "not found" message, Google should be able to help you find it.

**Comment by spaul13** [comment]
Yes found. Now It ran properly. Thanks a lot for your help.
