### ISSUE TITLE
Few errors while making this custom kernel 

### ISSUE THREAD

**Issue by spaul13** [nathanchance/wahoo#7]
While making the custom android kernel, right now I am getting this error. Can u please tell me how to resolve this? FYI. I just selected few driver support (e.g. Realtek, Ralink wifi usb driver support) by using "make menuconfig".

**_drivers/staging/qcacld-3.0/uapi/linux/qca_vendor.h:5356:43: error: passing argument 2 of 'cfg80211_vendor_event_alloc' makes pointer from integer without a cast [-Werror]
  skb = cfg80211_vendor_event_alloc(wiphy, approxlen, event_idx, gfp);
                                           ^
In file included from drivers/staging/qcacld-3.0/core/hdd/inc/wlan_hdd_assoc.h:41:0,
                 from drivers/staging/qcacld-3.0/core/hdd/inc/wlan_hdd_includes.h:46,
                 from drivers/staging/qcacld-3.0/core/hdd/src/wlan_hdd_assoc.c:35:
include/net/cfg80211.h:4684:1: note: expected 'struct wireless_dev *' but argument is of type 'int'
 cfg80211_vendor_event_alloc(struct wiphy *wiphy, struct wireless_dev *wdev,
 ^
In file included from drivers/staging/qcacld-3.0/core/hdd/src/wlan_hdd_cfg80211.h:37:0,
                 from drivers/staging/qcacld-3.0/core/hdd/inc/wlan_hdd_main.h:54,
                 from drivers/staging/qcacld-3.0/core/hdd/inc/wlan_hdd_includes.h:48,
                 from drivers/staging/qcacld-3.0/core/hdd/src/wlan_hdd_assoc.c:35:
drivers/staging/qcacld-3.0/uapi/linux/qca_vendor.h:5356:8: error: too few arguments to function 'cfg80211_vendor_event_alloc'
  skb = cfg80211_vendor_event_alloc(wiphy, approxlen, event_idx, gfp);
        ^
In file included from drivers/staging/qcacld-3.0/core/hdd/inc/wlan_hdd_assoc.h:41:0,
                 from drivers/staging/qcacld-3.0/core/hdd/inc/wlan_hdd_includes.h:46,
                 from drivers/staging/qcacld-3.0/core/hdd/src/wlan_hdd_assoc.c:35:
include/net/cfg80211.h:4684:1: note: declared here
 cfg80211_vendor_event_alloc(struct wiphy *wiphy, struct wireless_dev *wdev,
 ^
In file included from drivers/staging/qcacld-3.0/core/hdd/inc/wlan_hdd_main.h:54:0,
                 from drivers/staging/qcacld-3.0/core/hdd/inc/wlan_hdd_includes.h:48,
                 from drivers/staging/qcacld-3.0/core/hdd/src/wlan_hdd_assoc.c:35:
drivers/staging/qcacld-3.0/core/hdd/src/wlan_hdd_cfg80211.h: At top level:
drivers/staging/qcacld-3.0/core/hdd/src/wlan_hdd_cfg80211.h:503:1: error: redefinition of 'backported_cfg80211_vendor_event_alloc'
 backported_cfg80211_vendor_event_alloc(struct wiphy *wiphy,
 ^
In file included from drivers/staging/qcacld-3.0/core/hdd/src/wlan_hdd_cfg80211.h:37:0,
                 from drivers/staging/qcacld-3.0/core/hdd/inc/wlan_hdd_main.h:54,
                 from drivers/staging/qcacld-3.0/core/hdd/inc/wlan_hdd_includes.h:48,
                 from drivers/staging/qcacld-3.0/core/hdd/src/wlan_hdd_assoc.c:35:
drivers/staging/qcacld-3.0/uapi/linux/qca_vendor.h:5349:1: note: previous definition of 'backported_cfg80211_vendor_event_alloc' was here
 backported_cfg80211_vendor_event_alloc(struct wiphy *wiphy,
 ^
In file included from drivers/staging/qcacld-3.0/core/hdd/inc/wlan_hdd_main.h:54:0,
                 from drivers/staging/qcacld-3.0/core/hdd/inc/wlan_hdd_includes.h:48,
                 from drivers/staging/qcacld-3.0/core/hdd/src/wlan_hdd_assoc.c:35:
drivers/staging/qcacld-3.0/core/hdd/src/wlan_hdd_cfg80211.h: In function 'backported_cfg80211_vendor_event_alloc':
drivers/staging/qcacld-3.0/core/hdd/src/wlan_hdd_cfg80211.h:510:43: error: passing argument 2 of 'backported_cfg80211_vendor_event_alloc' makes pointer from integer without a cast [-Werror]
  skb = cfg80211_vendor_event_alloc(wiphy, approxlen, event_idx, gfp);
                                           ^
drivers/staging/qcacld-3.0/core/hdd/src/wlan_hdd_cfg80211.h:503:1: note: expected 'struct wireless_dev *' but argument is of type 'int'
 backported_cfg80211_vendor_event_alloc(struct wiphy *wiphy,
 ^
In file included from drivers/staging/qcacld-3.0/core/hdd/src/wlan_hdd_cfg80211.h:37:0,
                 from drivers/staging/qcacld-3.0/core/hdd/inc/wlan_hdd_main.h:54,
                 from drivers/staging/qcacld-3.0/core/hdd/inc/wlan_hdd_includes.h:48,
                 from drivers/staging/qcacld-3.0/core/hdd/src/wlan_hdd_assoc.c:35:
drivers/staging/qcacld-3.0/uapi/linux/qca_vendor.h:5377:37: error: too few arguments to function 'backported_cfg80211_vendor_event_alloc'
 #define cfg80211_vendor_event_alloc backported_cfg80211_vendor_event_alloc
                                     ^
drivers/staging/qcacld-3.0/core/hdd/src/wlan_hdd_cfg80211.h:510:8: note: in expansion of macro 'cfg80211_vendor_event_alloc'
  skb = cfg80211_vendor_event_alloc(wiphy, approxlen, event_idx, gfp);
        ^
In file included from drivers/staging/qcacld-3.0/core/hdd/inc/wlan_hdd_main.h:54:0,
                 from drivers/staging/qcacld-3.0/core/hdd/inc/wlan_hdd_includes.h:48,
                 from drivers/staging/qcacld-3.0/core/hdd/src/wlan_hdd_assoc.c:35:
drivers/staging/qcacld-3.0/core/hdd/src/wlan_hdd_cfg80211.h:503:1: note: declared here
 backported_cfg80211_vendor_event_alloc(struct wiphy *wiphy,
 ^
drivers/staging/qcacld-3.0/core/hdd/src/wlan_hdd_cfg80211.h: In function 'wlan_hdd_cfg80211_indicate_disconnect':
drivers/staging/qcacld-3.0/core/hdd/src/wlan_hdd_cfg80211.h:559:2: error: too few arguments to function 'cfg80211_disconnected'
  cfg80211_disconnected(dev, reason, NULL, 0,
  ^
In file included from drivers/staging/qcacld-3.0/core/hdd/inc/wlan_hdd_assoc.h:41:0,
                 from drivers/staging/qcacld-3.0/core/hdd/inc/wlan_hdd_includes.h:46,
                 from drivers/staging/qcacld-3.0/core/hdd/src/wlan_hdd_assoc.c:35:
include/net/cfg80211.h:4961:6: note: declared here
 void cfg80211_disconnected(struct net_device *dev, u16 reason,
      ^
  CC      drivers/platform/msm/ipa/ipa_v3/ipa_dma.o
  CC      drivers/soc/qcom/msm_bus/msm_bus_bimc_adhoc.o
drivers/staging/qcacld-3.0/core/hdd/src/wlan_hdd_assoc.c: In function 'hdd_dis_connect_handler':
drivers/staging/qcacld-3.0/core/hdd/src/wlan_hdd_assoc.c:1607:3: error: implicit declaration of function 'INIT_COMPLETION' [-Werror=implicit-function-declaration]
   INIT_COMPLETION(pAdapter->disconnect_comp_var);
   ^
In file included from include/linux/percpu_counter.h:15:0,
                 from include/linux/proportions.h:12,
                 from include/linux/sched.h:43,
                 from ./arch/arm64/include/asm/compat.h:25,
                 from ./arch/arm64/include/asm/stat.h:23,
                 from include/linux/stat.h:5,
                 from include/linux/module.h:10,
                 from drivers/staging/qcacld-3.0/core/hdd/inc/wlan_hdd_includes.h:38,
                 from drivers/staging/qcacld-3.0/core/hdd/src/wlan_hdd_assoc.c:35:
drivers/staging/qcacld-3.0/core/hdd/src/wlan_hdd_assoc.c: In function 'hdd_roam_ibss_indication_handler':
include/linux/gfp.h:240:20: error: passing argument 3 of 'cfg80211_ibss_joined' makes pointer from integer without a cast [-Werror]
 #define GFP_KERNEL (__GFP_RECLAIM | __GFP_IO | __GFP_FS)
                    ^
drivers/staging/qcacld-3.0/core/hdd/src/wlan_hdd_assoc.c:3272:11: note: in expansion of macro 'GFP_KERNEL'
           GFP_KERNEL);
           ^
In file included from drivers/staging/qcacld-3.0/core/hdd/inc/wlan_hdd_assoc.h:41:0,
                 from drivers/staging/qcacld-3.0/core/hdd/inc/wlan_hdd_includes.h:46,
                 from drivers/staging/qcacld-3.0/core/hdd/src/wlan_hdd_assoc.c:35:
include/net/cfg80211.h:4532:6: note: expected 'struct ieee80211_channel *' but argument is of type 'unsigned int'
 void cfg80211_ibss_joined(struct net_device *dev, const u8 *bssid,
      ^
drivers/staging/qcacld-3.0/core/hdd/src/wlan_hdd_assoc.c:3271:4: error: too few arguments to function 'cfg80211_ibss_joined'
    cfg80211_ibss_joined(pAdapter->dev, bss->bssid,
    ^
In file included from drivers/staging/qcacld-3.0/core/hdd/inc/wlan_hdd_assoc.h:41:0,
                 from drivers/staging/qcacld-3.0/core/hdd/inc/wlan_hdd_includes.h:46,
                 from drivers/staging/qcacld-3.0/core/hdd/src/wlan_hdd_assoc.c:35:
include/net/cfg80211.h:4532:6: note: declared here
 void cfg80211_ibss_joined(struct net_device *dev, const u8 *bssid,
      ^
cc1: all warnings being treated as errors
scripts/Makefile.build:299: recipe for target 'drivers/staging/qcacld-3.0/core/hdd/src/wlan_hdd_assoc.o' failed
make[3]: *** [drivers/staging/qcacld-3.0/core/hdd/src/wlan_hdd_assoc.o] Error 1
scripts/Makefile.build:551: recipe for target 'drivers/staging/qcacld-3.0' failed
make[2]: *** [drivers/staging/qcacld-3.0] Error 2
scripts/Makefile.build:551: recipe for target 'drivers/staging' failed
make[1]: *** [drivers/staging] Error 2
make[1]: *** Waiting for unfinished jobs...._**

**Comment by nathanchance** [comment]
I don't mean to be rude or dismissive but as soon as you start making modifications to the kernel, you are on your own as I don't really have the time to help you figure out how to accomplish what you want to do. I am sure Google has a decent amount of resources and aid around this topic.

I will clue you in to why you are getting these errors though. qcacld-3.0 has `#ifdef` blocks that use `LINUX_VERSION_CODE` all over the place because it supports several different kernel versions. You've clearly downgraded the version like you mentioned in your email so the driver thinks you are on a different version than you actually are.

The proper thing is to research how to install the Linux headers (or properly build/configure the drivers) for this version.
